# Generated by Django 3.2.7 on 2023-11-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='title_en',
            field=models.CharField(default='Parcel', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='title_ru',
            field=models.CharField(default='Parcel', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='title_tk',
            field=models.CharField(default='Parcel', max_length=255, null=True, unique=True),
        ),
    ]
