# Generated by Django 3.2.7 on 2023-11-16 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20231116_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Brands'},
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='title',
        ),
    ]
