# Generated by Django 3.2.7 on 2023-10-26 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_product_sale_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='deal_product',
            new_name='deal_date',
        ),
    ]
