# Generated by Django 3.2.7 on 2023-12-06 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_wishlist_model_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True, default='I am am Amazing Vendor', null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='description_en',
            field=models.TextField(blank=True, default='I am am Amazing Vendor', null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='description_ru',
            field=models.TextField(blank=True, default='I am am Amazing Vendor', null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='description_tk',
            field=models.TextField(blank=True, default='I am am Amazing Vendor', null=True),
        ),
        migrations.AlterField(
            model_name='wishlist_model',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
