# Generated by Django 3.2.7 on 2023-10-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_deal_product_product_deal_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.TimeField(auto_now_add=True, null=True)),
                ('mail', models.CharField(default='dide@gmail.com.', max_length=100)),
                ('address', models.CharField(default='123 Main Street.', max_length=100)),
                ('phone', models.CharField(default='+123 (456) 789', max_length=100)),
                ('image', models.ImageField(default='logo.jpg', upload_to='base-index')),
            ],
        ),
    ]
