# Generated by Django 3.2.7 on 2023-11-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20231116_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='product_type_attributes',
            field=models.ManyToManyField(related_name='product_type_attributes', through='core.ProductTypeAttribute', to='core.ProductAttribute'),
        ),
    ]
