# Generated by Django 3.2.7 on 2023-10-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_maininfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maininfo',
            name='hours',
        ),
        migrations.AddField(
            model_name='maininfo',
            name='from_hours',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='to_hours',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
