# Generated by Django 3.2.7 on 2023-12-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20231206_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ordering',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
