# Generated by Django 3.2.7 on 2023-10-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20231029_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_mainpage_status',
            field=models.CharField(blank=True, choices=[('new', 'New Products'), ('top_selling', 'Top Selling'), ('trending_products', 'Trending Products'), ('recent', 'Recently Added'), ('top_rated', 'Top Rated')], max_length=20, null=True),
        ),
    ]
