# Generated by Django 3.2.7 on 2023-10-29 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_product_mainpage_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
    ]
