# Generated by Django 3.2.7 on 2023-11-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20231116_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='Parcel', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_en',
            field=models.CharField(default='Parcel', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_ru',
            field=models.CharField(default='Parcel', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_tk',
            field=models.CharField(default='Parcel', max_length=100, null=True),
        ),
    ]
