# Generated by Django 3.2.7 on 2023-10-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_mainslider_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_1', models.ImageField(default='logo.jpg', upload_to='base-index')),
                ('banner_2', models.ImageField(default='logo.jpg', upload_to='base-index')),
                ('banner_3', models.ImageField(default='logo.jpg', upload_to='base-index')),
                ('banner_4', models.ImageField(default='logo.jpg', upload_to='base-index')),
            ],
        ),
        migrations.RenameModel(
            old_name='MainSlider',
            new_name='Slider',
        ),
    ]
