# Generated by Django 3.2.7 on 2023-10-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20231030_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='maininfo',
            name='name',
            field=models.CharField(default='Dide', max_length=100),
        ),
    ]
