# Generated by Django 3.2.7 on 2023-11-02 04:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_maininfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='This is the product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='This is the product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_tk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='This is the product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(default='Fresh Pear', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(default='Fresh Pear', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_tk',
            field=models.CharField(default='Fresh Pear', max_length=100, null=True),
        ),
    ]
