# Generated by Django 3.2.7 on 2023-11-02 13:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20231102_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='I am am Amazing Vendor', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='I am am Amazing Vendor', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='description_tk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='I am am Amazing Vendor', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='title_en',
            field=models.CharField(default='Nestify', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='title_ru',
            field=models.CharField(default='Nestify', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='title_tk',
            field=models.CharField(default='Nestify', max_length=100, null=True),
        ),
    ]
