# Generated by Django 3.2.7 on 2023-11-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20231102_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='logo.jpg', upload_to='category'),
        ),
    ]
