# Generated by Django 3.2.7 on 2023-11-03 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_kategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kategory',
        ),
    ]
